spec:
  template:
    spec:
      containers:
        - env:
          - name: spring_jpa_database
            value: postgresql
          - name: spring_datasource_url
            valueFrom:
              secretKeyRef:
                name: postgresql-security
                key: spring.datasource.url
          - name: spring_datasource_username
            valueFrom:
              secretKeyRef:
                name: postgresql-security
                key: spring.datasource.username
          - name: spring_datasource_password
            valueFrom:
              secretKeyRef:
                name: postgresql-security
                key: spring.datasource.password
          